title: Le Guide pour débutants sur la Microbrasserie Québécoise
description: Guide explicatif sur les styles de bière, les produits québécois, la vaisselle ainsi qu'une "caisse découverte" préfaite.
google_analytics:
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
theme: jekyll-theme-minimal